spring:
  application:
    name: api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:// 43.200.131.34:3306/turingdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    defer-datasource-initialization: true
#    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob:
            '[non_contextual_creation]': true
        '[format_sql]': true
    show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
jwt:
  iss: turing.co.kr
  exp: 24 * 60 * 60 * 1000
  secret: turingturingturingturingturingturingturingturingturingturingturingturingturingturingturingturingturingturingturingturingturingturingturingturing